service: serverless-blog

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-2
  environment:
    MONGO_URI: ${env:MONGO_URI}

package:
  include:
    - src/views/**/*
    - src/public/**/*

functions:
  app:
    handler: dist/index.handler
    events:
      - http:
          path: /
          method: ANY

      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-express
  - serverless-offline

